---
- name: Add 'public_html', 'logs' and '.ssh' dir to /etc/skel
  file: path="/etc/skel/{{ item }}" state=directory
  loop:
    - public_html
    - logs
    - .ssh

- name: Add users
  user:
    name: "{{item.user}}"
    shell: /bin/bash
    skeleton: /etc/skel
  when: item.user
  with_items: "{{sites}}"

- name: Ensure logs ownership is correct
  file:
    path: /home/{{item.user}}/logs
    state: directory
    recurse: yes
    owner: "{{item.user}}"
    group: "{{item.user}}"
  when: item.user
  with_items: "{{sites}}"
