---
- name: Add 'public_html', 'logs' and '.ssh' dir to /etc/skel
  file: path="/etc/skel/{{ item }}" state=directory
  loop:
    - public_html
    - logs
    - .ssh

- name: Add users for sites
  user:
    name: "{{item.user}}"
    shell: /bin/bash
    skeleton: /etc/skel
  when: item.user
  with_items: "{{sites}}"

- name: Ensure logs ownership is correct
  file:
    path: /home/{{item.user}}/logs
    state: directory
    recurse: yes
    owner: "{{item.user}}"
    group: "{{item.user}}"
  when: item.user
  with_items: "{{sites}}"

- name: Set up logrotate for log files
  copy:
    content: |
      /home/{{item.user}}/logs/*.log {
        missingok
        notifempty
        rotate 4
        create 644 {{item.user}} {{item.user}}
        size 10k
      }
    dest: /etc/logrotate.d/{{item.user}}
  with_items: "{{sites}}"