---
# This deps dir is used in the cronjobs of the football-core project.
- name: Create dependencies dir for Football-core
  file:
    state: directory
    path: "{{ scrape_deps.directory }}"
    mode: '0755'
    owner: football-core
    group: football-core

- name: Include Terraform variables used to setup the DB
  include_vars:
    file: ../../../../terraform.tfvars.json
    name: terraform_vars

- name: Include variables used to send emails and place bets
  include_vars:
    file: ../files/football_core_secrets.json
    name: email_and_bet_secrets

- name: Create file for RDS environment variables
  file:
    path: /home/football-core/.environment
    state: touch
    mode: 0400
    owner: football-core
    group: football-core
  changed_when: False

- name: Set RDS URL as environment variable to allow Football Core & Betting API to connect
  lineinfile:
    path: /home/football-core/.environment
    line: "export DB_URL={{ tf_rds_url }}"

- name: Set DB name as environment variable to allow Football Core & Betting API to connect
  lineinfile:
    path: /home/football-core/.environment
    line: "export DB_NAME=football_betting"

- name: Set DB user as environment variable to allow Football Core & Betting API to connect
  lineinfile:
    path: /home/football-core/.environment
    line: "export DB_USER={{ terraform_vars.db_username }}"

- name: Set DB password as environment variable to allow Football Core & Betting API to connect
  lineinfile:
    path: /home/football-core/.environment
    line: "export DB_PASS={{ terraform_vars.db_password }}"

- name: Set Octave predictor path as environment variable to allow Football Core to predict matches
  lineinfile:
    path: /home/football-core/.environment
    line: "export OCTAVE_PREDICT_FILE={{ octave_prediction.predict_url }}"

- name: Set Octave predictor theta path as an environment variable to allow Football Core to predict matches
  lineinfile:
    path: /home/football-core/.environment
    line: "export OCTAVE_THETA_PATH={{ octave_prediction.predict_thetas_location }}"

- name: Set Chromedriver location as an environment variable to allow Football Core to place bets and scrape odds
  lineinfile:
    path: /home/football-core/.environment
    line: "export CHROMEDRIVER_PATH={{ scrape_deps.chromedriver }}"

- name: Set admin email for Football Core to send notifications to
  lineinfile:
    path: /home/football-core/.environment
    line: "export ADMIN_EMAIL={{ email_and_bet_secrets.admin_email.username }}"

- name: Set email for Football Core to send emails from
  lineinfile:
    path: /home/football-core/.environment
    line: "export SENDING_EMAIL_ACC={{ email_and_bet_secrets.sending_email.username }}"

- name: Set password for Football Core to send emails from
  lineinfile:
    path: /home/football-core/.environment
    line: "export SENDING_EMAIL_PASS={{ email_and_bet_secrets.sending_email.password }}"

- name: Set email for Unibet account
  lineinfile:
    path: /home/football-core/.environment
    line: "export UNIBET_USER={{ email_and_bet_secrets.unibet.username }}"

- name: Set password for Unibet account
  lineinfile:
    path: /home/football-core/.environment
    line: "export UNIBET_PASS={{ email_and_bet_secrets.unibet.password }}"
