---
- name: Include Terraform variables used to setup the DB
  include_vars:
    file: ../../../../terraform.tfvars.json
    name: terraform_vars

- name: Include variables used to send emails
  include_vars:
    file: ../files/email_secrets.json
    name: email_secrets

- name: Include variables used to place bets
  include_vars:
    file: ../files/betfair_secrets.json
    name: betfair_secrets

- name: Create file for RDS environment variables
  file:
    path: /home/football-core/.environment
    state: touch
    mode: 0400
    owner: football-core
    group: football-core
  changed_when: False

- name: Set RDS URL as environment variable to allow Football Core & Betting API to connect
  lineinfile:
    path: /home/football-core/.environment
    line: "export DB_URL={{ tf_rds_url }}"

- name: Set DB name as environment variable to allow Football Core & Betting API to connect
  lineinfile:
    path: /home/football-core/.environment
    line: "export DB_NAME=football_betting"

- name: Set DB user as environment variable to allow Football Core & Betting API to connect
  lineinfile:
    path: /home/football-core/.environment
    line: "export DB_USER={{ terraform_vars.db_username }}"

- name: Set DB password as environment variable to allow Football Core & Betting API to connect
  lineinfile:
    path: /home/football-core/.environment
    line: "export DB_PASS={{ terraform_vars.db_password }}"

- name: Set Octave predictor path as environment variable to allow Football Core to predict matches
  lineinfile:
    path: /home/football-core/.environment
    line: "export OCTAVE_PREDICT_FILE={{ octave_prediction.predict_url }}"

- name: Set Octave predictor theta path as an environment variable to allow Football Core to predict matches
  lineinfile:
    path: /home/football-core/.environment
    line: "export OCTAVE_THETA_PATH={{ octave_prediction.predict_thetas_location }}"

- name: Set admin email as an environment variable for Football Core to send notifications to
  lineinfile:
    path: /home/football-core/.environment
    line: "export ADMIN_EMAIL={{ email_secrets.admin_email.username }}"

- name: Set email for Football Core to send emails from as an environment variable
  lineinfile:
    path: /home/football-core/.environment
    line: "export SENDING_EMAIL_ACC={{ email_secrets.sending_email.username }}"

- name: Add directory for Betfair P12 cert
  file:
    state: directory
    path: "{{ betfair.p12.dir }}"
    mode: '0700'
    owner: football-core
    group: football-core

- name: Copy P12 cert to remote machine
  copy:
    src: "../files/{{ betfair.p12.name }}"
    dest: "{{ betfair.p12.dir }}/{{ betfair.p12.name }}"
    mode: '0400'
    owner: football-core
    group: football-core

- name: Set Betfair P12 cert path (used to log into Betfair API) as an environment variable
  lineinfile:
    path: /home/football-core/.environment
    line: "export BETFAIR_P12_PATH={{ betfair.p12.dir }}/{{ betfair.p12.name }}"

- name: Set Betfair P12 cert password as an environment variable
  lineinfile:
    path: /home/football-core/.environment
    line: "export BETFAIR_P12_PASS={{ betfair_secrets.p12.password }}"

- name: Set Betfair account username as an environment variable
  lineinfile:
    path: /home/football-core/.environment
    line: "export BETFAIR_ACC_USER={{ betfair_secrets.account.username }}"

- name: Set Betfair account password as an environment variable
  lineinfile:
    path: /home/football-core/.environment
    line: "export BETFAIR_ACC_PASS={{ betfair_secrets.account.password }}"

- name: Set Betfair app key as an environment variable
  lineinfile:
    path: /home/football-core/.environment
    line: "export BETFAIR_APP_KEY={{ betfair_secrets.app_key }}"
