---
- name: Install Apache2 with modules
  apt: name="{{ item }}" state=latest update_cache=yes
  loop:
    - apache2
    - libapache2-mpm-itk

- name: Enable Apache2 mpm_itk
  apache2_module:
    state: present
    name: mpm_itk

- name: Copy default VHost file
  copy:
    src: ../files/apache2_default_template.conf
    dest: "{{apache2.default_file}}"
    owner: www-data
    group: www-data
    mode: 0644

- name: Change port to 8080
  copy:
    src: ../files/ports.conf
    dest: /etc/apache2/ports.conf
    owner: www-data
    group: www-data
    mode: 0644
  notify: Restart Apache2

- name: Start and enable Apache2
  service:
    name: apache2
    state: started
    enabled: yes