---
- name: Check if Geckodriver already exists
  stat:
    path: "{{ scrape_deps.geckodriver }}"
  register: geckodriver_location

- name: Download Geckodriver
  unarchive:
    remote_src: yes
    src: "https://github.com/mozilla/geckodriver/releases/download/v0.30.0/geckodriver-v0.30.0-linux64.tar.gz"
    dest: "{{ scrape_deps.directory }}"
  when: geckodriver_location.stat.exists == False

- name: Make Geckodriver owned by football-core and add executable perms
  file:
    path: "{{ scrape_deps.geckodriver }}"
    mode: '0555'
    owner: football-core
    group: football-core