nginx:
  default_file: /etc/nginx/sites-available/default.conf
  api_file: /etc/nginx/sites-available/tomcat-proxy-default.conf

apache2:
  default_file: /etc/apache2/sites-available/default.conf

# These usernames may be hardcoded in the Ansible role 'application-specific', so please ensure to change these throughout the project.
sites:
  - url: football.petersprojects.co.uk
    user: frontend
    isApi: false
    tomcat_endpoint: null
    ssh_key_name: github-actions-frontend
  - url: api.football.petersprojects.co.uk
    user: tomcat-github-actions
    isApi: true
    tomcat_endpoint: football
    ssh_key_name: github-actions-tomcat
  - url: null
    user: football-core
    isApi: false
    tomcat_endpoint: null
    ssh_key_name: football-core

octave_prediction:
  predict_url: /home/football-core/octave-prediction/logisticRegression/FootballTrainingProbabilitiesScorePredict.m
  predict_thetas_location: /home/football-core/octave-prediction/logisticRegression/logistic_regression_thetas.csv

betfair:
  p12:
    dir: /home/football-core/keys
    name: client-2048.p12