nginx:
  default_file: /etc/nginx/sites-available/default.conf
  api_file: /etc/nginx/sites-available/tomcat-proxy-default.conf

apache2:
  default_file: /etc/apache2/sites-available/default.conf

sites:
  - url: football.petersprojects.co.uk
    user: frontend
    isApi: false
    tomcat_endpoint: null
    ssh_key_name: github-actions-frontend
  - url: api.football.petersprojects.co.uk
    user: tomcat-github-actions
    isApi: true
    tomcat_endpoint: football
    ssh_key_name: github-actions-tomcat