---
# Oracle Cloud by default restricts instance access via iptables to just SSH
- name: Allow traffic on TCP port 80 (HTTP)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 80
    jump: ACCEPT
    action: insert
  register: iptables_http

- name: Allow traffic on TCP port 443 (HTTPS)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 443
    jump: ACCEPT
    action: insert
  register: iptables_https

- name: Allow traffic on TCP port 3306 (MySQL)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 3306
    jump: ACCEPT
    action: insert
  register: iptables_mysql

- name: Allow traffic on TCP port 8000 (Tomcat)
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_port: 8000
    jump: ACCEPT
    action: insert
  register: iptables_tomcat

- name: Save iptables rules
  shell: iptables-save > /etc/iptables/rules.v4
  when: iptables_http.changed or iptables_https.changed or iptables_mysql.changed or iptables_tomcat.changed