---
- name: Install Nginx
  apt: name="{{ item }}" state=latest update_cache=yes
  loop:
    - nginx

- name: Copy default VHost file
  copy:
    src: ../files/default_template.conf
    dest: "{{nginx.default_file}}"
    owner: www-data
    group: www-data
    mode: 0644

- name: Copy VHost for port 80 to redirect requests to port 443
  copy:
    src: ../files/redirect_port_80_to_443.conf
    dest: /etc/nginx/sites-available/default
  notify: Restart Nginx

- name: Create snippets dir
  file:
    path: /etc/nginx/snippets
    state: directory

- name: Copy snippets
  synchronize:
    src: roles/nginx/files/snippets
    dest: /etc/nginx
    mode: push
  notify: Restart Nginx
